// <auto-generated />
using System;
using Controlume.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Controlume.Web.Data.Migrations
{
    [DbContext(typeof(ControlumeDbContext))]
    [Migration("20260807033721_AddFormaPagamentoECancelamentoVenda")]
    partial class AddFormaPagamentoECancelamentoVenda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Controlume.Web.Domain.FechamentoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_abertura");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fechamento");

                    b.Property<decimal?>("SaldoFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saldo_final");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorInicial")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_inicial");

                    b.HasKey("Id")
                        .HasName("pk_fechamentos_caixa");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("ix_fechamentos_caixa_status")
                        .HasFilter("status = 'Aberto'");

                    b.ToTable("fechamentos_caixa", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<bool>("ContaComoCaixaFisico")
                        .HasColumnType("boolean")
                        .HasColumnName("conta_como_caixa_fisico");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<bool>("RequerConfirmacaoRecebimento")
                        .HasColumnType("boolean")
                        .HasColumnName("requer_confirmacao_recebimento");

                    b.HasKey("Id")
                        .HasName("pk_formas_pagamento");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_formas_pagamento_nome");

                    b.ToTable("formas_pagamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            ContaComoCaixaFisico = true,
                            Nome = "Dinheiro",
                            RequerConfirmacaoRecebimento = false
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            ContaComoCaixaFisico = false,
                            Nome = "Cartão",
                            RequerConfirmacaoRecebimento = false
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            ContaComoCaixaFisico = false,
                            Nome = "Pix",
                            RequerConfirmacaoRecebimento = false
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            ContaComoCaixaFisico = false,
                            Nome = "Mercado Livre",
                            RequerConfirmacaoRecebimento = true
                        });
                });

            modelBuilder.Entity("Controlume.Web.Domain.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecoTabela")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_tabela");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_venda");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_itens_venda");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_venda_produto_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_itens_venda_venda_id");

                    b.ToTable("itens_venda", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtistaGrupo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("artista_grupo");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_estoque");

                    b.Property<int>("TipoProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_produto_id");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("TipoProdutoId")
                        .HasDatabaseName("ix_produtos_tipo_produto_id");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.Sangria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("FechamentoCaixaId")
                        .HasColumnType("integer")
                        .HasColumnName("fechamento_caixa_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("motivo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_sangrias");

                    b.HasIndex("FechamentoCaixaId")
                        .HasDatabaseName("ix_sangrias_fechamento_caixa_id");

                    b.ToTable("sangrias", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.TipoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tipos_produto");

                    b.ToTable("tipos_produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Nome = "Disco"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Nome = "CD"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Nome = "DVD"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Nome = "Eletrônico"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Nome = "Avulso"
                        });
                });

            modelBuilder.Entity("Controlume.Web.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_login");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelada")
                        .HasColumnType("boolean")
                        .HasColumnName("cancelada");

                    b.Property<int?>("CanceladoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("cancelado_por_usuario_id");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cancelamento");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<int>("FechamentoCaixaId")
                        .HasColumnType("integer")
                        .HasColumnName("fechamento_caixa_id");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_vendas");

                    b.HasIndex("CanceladoPorUsuarioId")
                        .HasDatabaseName("ix_vendas_cancelado_por_usuario_id");

                    b.HasIndex("FechamentoCaixaId")
                        .HasDatabaseName("ix_vendas_fechamento_caixa_id");

                    b.ToTable("vendas", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.VendaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_recebimento");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento_id");

                    b.Property<bool>("Recebido")
                        .HasColumnType("boolean")
                        .HasColumnName("recebido");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_venda_pagamentos");

                    b.HasIndex("FormaPagamentoId")
                        .HasDatabaseName("ix_venda_pagamentos_forma_pagamento_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_venda_pagamentos_venda_id");

                    b.ToTable("venda_pagamentos", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.ItemVenda", b =>
                {
                    b.HasOne("Controlume.Web.Domain.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_venda_produtos_produto_id");

                    b.HasOne("Controlume.Web.Domain.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_venda_vendas_venda_id");

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Controlume.Web.Domain.Produto", b =>
                {
                    b.HasOne("Controlume.Web.Domain.TipoProduto", "TipoProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("TipoProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_tipos_produto_tipo_produto_id");

                    b.Navigation("TipoProduto");
                });

            modelBuilder.Entity("Controlume.Web.Domain.Sangria", b =>
                {
                    b.HasOne("Controlume.Web.Domain.FechamentoCaixa", "FechamentoCaixa")
                        .WithMany("Sangrias")
                        .HasForeignKey("FechamentoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sangrias_fechamentos_caixa_fechamento_caixa_id");

                    b.Navigation("FechamentoCaixa");
                });

            modelBuilder.Entity("Controlume.Web.Domain.Venda", b =>
                {
                    b.HasOne("Controlume.Web.Domain.Usuario", "CanceladoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CanceladoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vendas_usuarios_cancelado_por_usuario_id");

                    b.HasOne("Controlume.Web.Domain.FechamentoCaixa", "FechamentoCaixa")
                        .WithMany("Vendas")
                        .HasForeignKey("FechamentoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendas_fechamentos_caixa_fechamento_caixa_id");

                    b.Navigation("CanceladoPorUsuario");

                    b.Navigation("FechamentoCaixa");
                });

            modelBuilder.Entity("Controlume.Web.Domain.VendaPagamento", b =>
                {
                    b.HasOne("Controlume.Web.Domain.FormaPagamento", "FormaPagamento")
                        .WithMany("Pagamentos")
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venda_pagamentos_formas_pagamento_forma_pagamento_id");

                    b.HasOne("Controlume.Web.Domain.Venda", "Venda")
                        .WithMany("Pagamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venda_pagamentos_vendas_venda_id");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Controlume.Web.Domain.FechamentoCaixa", b =>
                {
                    b.Navigation("Sangrias");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Controlume.Web.Domain.FormaPagamento", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Controlume.Web.Domain.TipoProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Controlume.Web.Domain.Venda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
