using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Controlume.Web.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddFormaPagamentoECancelamentoVenda : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // A ordem aqui é o ponto todo desta migration: já existem venda_pagamentos em produção
            // com o valor string antigo, então a coluna nova nasce nullable, é preenchida a partir
            // do texto, só então vira NOT NULL — e só depois disso a coluna antiga sai.

            migrationBuilder.CreateTable(
                name: "formas_pagamento",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    nome = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    ativo = table.Column<bool>(type: "boolean", nullable: false),
                    conta_como_caixa_fisico = table.Column<bool>(type: "boolean", nullable: false),
                    requer_confirmacao_recebimento = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_formas_pagamento", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_formas_pagamento_nome",
                table: "formas_pagamento",
                column: "nome",
                unique: true);

            migrationBuilder.InsertData(
                table: "formas_pagamento",
                columns: new[] { "id", "ativo", "conta_como_caixa_fisico", "nome", "requer_confirmacao_recebimento" },
                values: new object[,]
                {
                    { 1, true, true, "Dinheiro", false },
                    { 2, true, false, "Cartão", false },
                    { 3, true, false, "Pix", false },
                    { 4, true, false, "Mercado Livre", true }
                });

            // Os ids do INSERT acima são explícitos, e "GENERATED BY DEFAULT AS IDENTITY" não avança
            // a sequência quando o id vem escrito: sem este setval, a primeira forma criada pela tela
            // pediria id = 1 e bateria de frente com "Dinheiro".
            //
            // tipos_produto entra junto porque foi semeado do mesmo jeito no InitialCreate e carrega
            // exatamente o mesmo defeito — cadastrar um tipo novo hoje falha por PK duplicada até a
            // sequência passar de 5. Não é assunto desta rodada, mas é uma linha e o banco é o mesmo.
            migrationBuilder.Sql("""
                SELECT setval(
                    pg_get_serial_sequence('formas_pagamento', 'id'),
                    GREATEST(COALESCE((SELECT MAX(id) FROM formas_pagamento), 0), 1));

                SELECT setval(
                    pg_get_serial_sequence('tipos_produto', 'id'),
                    GREATEST(COALESCE((SELECT MAX(id) FROM tipos_produto), 0), 1));
                """);

            migrationBuilder.AddColumn<int>(
                name: "forma_pagamento_id",
                table: "venda_pagamentos",
                type: "integer",
                nullable: true);

            // O valor gravado era TipoPagamento.ToString() (HasConversion<string>), ou seja
            // 'Cartao' sem cedilha; 'Cartão' entra na lista só por segurança.
            migrationBuilder.Sql("""
                UPDATE venda_pagamentos SET forma_pagamento_id = CASE tipo_pagamento
                    WHEN 'Dinheiro' THEN 1
                    WHEN 'Cartao'   THEN 2
                    WHEN 'Cartão'   THEN 2
                    WHEN 'Pix'      THEN 3
                END;
                """);

            // Sem isto, um valor inesperado viraria NULL e o SET NOT NULL abaixo falharia com uma
            // mensagem que não diz nada sobre a causa. A migration inteira roda em transação:
            // este RAISE aborta e desfaz tudo.
            migrationBuilder.Sql("""
                DO $$
                DECLARE nao_mapeados text;
                BEGIN
                    SELECT string_agg(DISTINCT tipo_pagamento, ', ')
                      INTO nao_mapeados
                      FROM venda_pagamentos
                     WHERE forma_pagamento_id IS NULL;

                    IF nao_mapeados IS NOT NULL THEN
                        RAISE EXCEPTION
                            'Há venda_pagamentos com tipo_pagamento sem forma correspondente: %. Cadastre a forma e ajuste o mapeamento antes de migrar.',
                            nao_mapeados;
                    END IF;
                END $$;
                """);

            migrationBuilder.AlterColumn<int>(
                name: "forma_pagamento_id",
                table: "venda_pagamentos",
                type: "integer",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_venda_pagamentos_forma_pagamento_id",
                table: "venda_pagamentos",
                column: "forma_pagamento_id");

            migrationBuilder.AddForeignKey(
                name: "fk_venda_pagamentos_formas_pagamento_forma_pagamento_id",
                table: "venda_pagamentos",
                column: "forma_pagamento_id",
                principalTable: "formas_pagamento",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.DropColumn(
                name: "tipo_pagamento",
                table: "venda_pagamentos");

            migrationBuilder.AddColumn<bool>(
                name: "recebido",
                table: "venda_pagamentos",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "data_recebimento",
                table: "venda_pagamentos",
                type: "timestamp with time zone",
                nullable: true);

            // Toda venda registrada até aqui foi Dinheiro/Cartão/Pix — recebida por definição.
            // DataRecebimento fica nula: não há registro de quando, e inventar a data seria pior.
            migrationBuilder.Sql("UPDATE venda_pagamentos SET recebido = TRUE;");

            migrationBuilder.AddColumn<bool>(
                name: "cancelada",
                table: "vendas",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "motivo_cancelamento",
                table: "vendas",
                type: "character varying(300)",
                maxLength: 300,
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "data_cancelamento",
                table: "vendas",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "cancelado_por_usuario_id",
                table: "vendas",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_vendas_cancelado_por_usuario_id",
                table: "vendas",
                column: "cancelado_por_usuario_id");

            migrationBuilder.AddForeignKey(
                name: "fk_vendas_usuarios_cancelado_por_usuario_id",
                table: "vendas",
                column: "cancelado_por_usuario_id",
                principalTable: "usuarios",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_vendas_usuarios_cancelado_por_usuario_id",
                table: "vendas");

            migrationBuilder.DropIndex(
                name: "ix_vendas_cancelado_por_usuario_id",
                table: "vendas");

            migrationBuilder.DropColumn(
                name: "cancelado_por_usuario_id",
                table: "vendas");

            migrationBuilder.DropColumn(
                name: "data_cancelamento",
                table: "vendas");

            migrationBuilder.DropColumn(
                name: "motivo_cancelamento",
                table: "vendas");

            migrationBuilder.DropColumn(
                name: "cancelada",
                table: "vendas");

            migrationBuilder.DropColumn(
                name: "data_recebimento",
                table: "venda_pagamentos");

            migrationBuilder.DropColumn(
                name: "recebido",
                table: "venda_pagamentos");

            // Caminho inverso do Up: recria a coluna string, preenche a partir da FK e só então
            // derruba a FK. Formas criadas pela tela depois da migration não têm equivalente no
            // enum antigo, então o rollback só é possível enquanto ninguém usou uma delas.
            migrationBuilder.AddColumn<string>(
                name: "tipo_pagamento",
                table: "venda_pagamentos",
                type: "character varying(20)",
                maxLength: 20,
                nullable: true);

            migrationBuilder.Sql("""
                UPDATE venda_pagamentos SET tipo_pagamento = CASE forma_pagamento_id
                    WHEN 1 THEN 'Dinheiro'
                    WHEN 2 THEN 'Cartao'
                    WHEN 3 THEN 'Pix'
                END;
                """);

            migrationBuilder.Sql("""
                DO $$
                DECLARE nao_mapeados text;
                BEGIN
                    SELECT string_agg(DISTINCT f.nome, ', ')
                      INTO nao_mapeados
                      FROM venda_pagamentos p
                      JOIN formas_pagamento f ON f.id = p.forma_pagamento_id
                     WHERE p.tipo_pagamento IS NULL;

                    IF nao_mapeados IS NOT NULL THEN
                        RAISE EXCEPTION
                            'Não é possível reverter: há vendas pagas com formas que não existem no enum antigo (%).',
                            nao_mapeados;
                    END IF;
                END $$;
                """);

            migrationBuilder.AlterColumn<string>(
                name: "tipo_pagamento",
                table: "venda_pagamentos",
                type: "character varying(20)",
                maxLength: 20,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(20)",
                oldMaxLength: 20,
                oldNullable: true);

            migrationBuilder.DropForeignKey(
                name: "fk_venda_pagamentos_formas_pagamento_forma_pagamento_id",
                table: "venda_pagamentos");

            migrationBuilder.DropIndex(
                name: "ix_venda_pagamentos_forma_pagamento_id",
                table: "venda_pagamentos");

            migrationBuilder.DropColumn(
                name: "forma_pagamento_id",
                table: "venda_pagamentos");

            migrationBuilder.DropTable(
                name: "formas_pagamento");
        }
    }
}
