// <auto-generated />
using System;
using Controlume.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Controlume.Web.Data.Migrations
{
    [DbContext(typeof(ControlumeDbContext))]
    partial class ControlumeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Controlume.Web.Domain.FechamentoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_abertura");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fechamento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorInicial")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_inicial");

                    b.HasKey("Id")
                        .HasName("pk_fechamentos_caixa");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("ix_fechamentos_caixa_status")
                        .HasFilter("status = 'Aberto'");

                    b.ToTable("fechamentos_caixa", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecoTabela")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_tabela");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_venda");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_itens_venda");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_venda_produto_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_itens_venda_venda_id");

                    b.ToTable("itens_venda", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtistaGrupo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("artista_grupo");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_estoque");

                    b.Property<int>("TipoProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_produto_id");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("TipoProdutoId")
                        .HasDatabaseName("ix_produtos_tipo_produto_id");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.TipoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tipos_produto");

                    b.ToTable("tipos_produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Nome = "Disco"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Nome = "CD"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Nome = "DVD"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Nome = "Eletrônico"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Nome = "Avulso"
                        });
                });

            modelBuilder.Entity("Controlume.Web.Domain.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<int>("FechamentoCaixaId")
                        .HasColumnType("integer")
                        .HasColumnName("fechamento_caixa_id");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_vendas");

                    b.HasIndex("FechamentoCaixaId")
                        .HasDatabaseName("ix_vendas_fechamento_caixa_id");

                    b.ToTable("vendas", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.VendaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_pagamento");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_venda_pagamentos");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_venda_pagamentos_venda_id");

                    b.ToTable("venda_pagamentos", (string)null);
                });

            modelBuilder.Entity("Controlume.Web.Domain.ItemVenda", b =>
                {
                    b.HasOne("Controlume.Web.Domain.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_venda_produtos_produto_id");

                    b.HasOne("Controlume.Web.Domain.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_venda_vendas_venda_id");

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Controlume.Web.Domain.Produto", b =>
                {
                    b.HasOne("Controlume.Web.Domain.TipoProduto", "TipoProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("TipoProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_tipos_produto_tipo_produto_id");

                    b.Navigation("TipoProduto");
                });

            modelBuilder.Entity("Controlume.Web.Domain.Venda", b =>
                {
                    b.HasOne("Controlume.Web.Domain.FechamentoCaixa", "FechamentoCaixa")
                        .WithMany("Vendas")
                        .HasForeignKey("FechamentoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendas_fechamentos_caixa_fechamento_caixa_id");

                    b.Navigation("FechamentoCaixa");
                });

            modelBuilder.Entity("Controlume.Web.Domain.VendaPagamento", b =>
                {
                    b.HasOne("Controlume.Web.Domain.Venda", "Venda")
                        .WithMany("Pagamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venda_pagamentos_vendas_venda_id");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Controlume.Web.Domain.FechamentoCaixa", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Controlume.Web.Domain.TipoProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Controlume.Web.Domain.Venda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
